version: '3.9'

services:

  python:
    build: .
    container_name: fastapi_app
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    links:
      - "db:db"
    entrypoint: python app.py
    depends_on:
      - db

  db:
    image: postgres
    container_name: fastapi_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fastapi
    ports:
      - "8001:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data

  pgadmin:
    image: adminer
    container_name: fastapi_db_adminer
    restart: unless-stopped  
    ports:
      - 8002:8080
    volumes:
      - ./db/admin:/var/lib/postgresql/admin
    depends_on:
      - db
